export const DETAIL_PRODUCT = 'DETAIL_PRODUCT';
export const DETAIL_ORDER_PRODUCT = 'DETAIL_ORDER_PRODUCT';
export const DETAIL_BUYER_PRODUCT = 'DETAIL_BUYER_PRODUCT';
export const SET_DATA_ORDER_SELLER = 'SET_DATA_ORDER_SELLER';
export const SET_DATA_PRODUCT_SELLER = 'SET_DATA_PRODUCT_SELLER';
export const SET_DATA_ORDER_BUYER = 'SET_DATA_ORDER_BUYER';
