export const kota = [
  {label: 'Ambon', value: 'ambon'},
  {label: 'Balikpapan', value: 'balikpapan'},
  {label: 'Aceh', value: 'aceh'},
  {label: 'Lampung', value: 'lampung'},
  {label: 'Bandung', value: 'bandung'},
  {label: 'Banjar', value: 'banjar'},
  {label: 'Banjarbaru', value: 'banjarbaru'},
  {label: 'Banjarmasin', value: 'banjarmasin'},
  {label: 'Batam', value: 'batam'},
  {label: 'Batu', value: 'batu'},
  {label: 'Baubau', value: 'baubau'},
  {label: 'Bekasi', value: 'bekasi'},
  {label: 'Bengkulu', value: 'bengkulu'},
  {label: 'Bima', value: 'bima'},
  {label: 'Binjai', value: 'binjai'},
  {label: 'Bogor', value: 'bogor'},
  {label: 'Bontang', value: 'bontang'},
  {label: 'Bukittinggi', value: 'bukittinggi'},
  {label: 'Cilegon', value: 'cilegon'},
  {label: 'Cimahi', value: 'cimahi'},
  {label: 'Cirebon', value: 'cirebon'},
  {label: 'Denpasar', value: 'denpasar'},
  {label: 'Depok', value: 'depok'},
  {label: 'Dumai', value: 'dumai'},
  {label: 'Gorontalo', value: 'gorontalo'},
  {label: 'Gunungsitoli', value: 'gunungsitoli'},
  {label: 'Jakarta Barat', value: 'jakartabarat'},
  {label: 'Jakarta Pusat', value: 'jakartapusat'},
  {label: 'Jakarta Selatan', value: 'jakartaselatan'},
  {label: 'Jakarta Timur', value: 'jakartatimur'},
  {label: 'Jakarta Utara', value: 'jakartautara'},
  {label: 'Jambi', value: 'jambi'},
  {label: 'Jayapura', value: 'jayapura'},
  {label: 'Kediri', value: 'kediri'},
  {label: 'Kendari', value: 'kendari'},
  {label: 'Kotamobagu', value: 'kotamobagu'},
  {label: 'Kupang', value: 'kupang'},
  {label: 'Langsa', value: 'langsa'},
  {label: 'Lhokseumawe', value: 'lhokseumawe'},
  {label: 'Lubuklinggau', value: 'lubuklinggau'},
  {label: 'Madiun', value: 'madiun'},
  {label: 'Magelang', value: 'magelang'},
  {label: 'Makassar', value: 'makassar'},
  {label: 'Malang', value: 'malang'},
  {label: 'Manado', value: 'manado'},
  {label: 'Mataram', value: 'mataram'},
  {label: 'Medan', value: 'medan'},
  {label: 'Metro', value: 'metro'},
  {label: 'Mojokerto', value: 'mojokerto'},
  {label: 'Padang', value: 'padang'},
  {label: 'Padang Panjang', value: 'padangpanjang'},
  {label: 'Padang Sidempuan', value: 'padangsidempuan'},
  {label: 'Pagar Alam', value: 'pagaralam'},
  {label: 'Palangka Raya', value: 'palangkaraya'},
  {label: 'Palembang', value: 'palembang'},
  {label: 'Palopo', value: 'palopo'},
  {label: 'Palu', value: 'palu'},
  {label: 'Pangkalpinang', value: 'pangkalpinang'},
  {label: 'Parepare', value: 'parepare'},
  {label: 'Pariaman', value: 'pariaman'},
  {label: 'Pasuruan', value: 'pasuruan'},
  {label: 'Payakumbuh', value: 'payakumbuh'},
  {label: 'Pekalongan', value: 'pekalongan'},
  {label: 'Pekanbaru', value: 'pekanbaru'},
  {label: 'Pematangsiantar', value: 'pematangsiantar'},
  {label: 'Pontianak', value: 'pontianak'},
  {label: 'Prabumulih', value: 'prabumulih'},
  {label: 'Probolinggo', value: 'probolinggo'},
  {label: 'Sabang', value: 'sabang'},
  {label: 'Salatiga', value: 'salatiga'},
  {label: 'Samarinda', value: 'samarinda'},
  {label: 'Sawahlunto', value: 'sawahlunto'},
  {label: 'Semarang', value: 'semarang'},
  {label: 'Serang', value: 'serang'},
  {label: 'Sibolga', value: 'sibolga'},
  {label: 'Singkawang', value: 'singkawang'},
  {label: 'Solok', value: 'solok'},
  {label: 'Sorong', value: 'sorong'},
  {label: 'Subulussalam', value: 'subulussalam'},
  {label: 'Sukabumi', value: 'sukabumi'},
  {label: 'Sungai Penuh', value: 'sungaipenuh'},
  {label: 'Surabaya', value: 'surabaya'},
  {label: 'Surakarta', value: 'surakarta'},
  {label: 'Tangerang Selatan', value: 'tangerangselatan'},
  {label: 'Tangerang', value: 'tangerang'},
  {label: 'Tanjungbalai', value: 'tanjungbalai'},
  {label: 'Tanjungpinang', value: 'tanjungpinang'},
  {label: 'Tarakan', value: 'tarakan'},
  {label: 'Tasikmalaya', value: 'tasikmalaya'},
  {label: 'Tebing Tinggi', value: 'tebingtinggi'},
  {label: 'Tegal', value: 'tegal'},
  {label: 'Ternate', value: 'ternate'},
  {label: 'Tidore Kepulauan', value: 'tidorekepulauan'},
  {label: 'Tomohon', value: 'tomohon'},
  {label: 'Tual', value: 'tual'},
  {label: 'Yogyakarta', value: 'yogyakarta'},
];
