export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const SET_LENGTH_PRODUCTS = 'SET_LENGTH_PRODUCTS';
export const DATA_CATEGORY = 'DATA_CATEGORY';
export const PRODUCT_CATEGORY = 'PRODUCT_CATEGORY';
export const BANNER = 'BANNER';
